version: 0.2
phases:
  install:
    commands:
      - yum -y install jq
      - curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq 'to_entries | [ .[] | select(.key | (contains("Expiration") or contains("RoleArn"))  | not) ] |  map(if .key == "AccessKeyId" then . + {"key":"AWS_ACCESS_KEY_ID"} else . end) | map(if .key == "SecretAccessKey" then . + {"key":"AWS_SECRET_ACCESS_KEY"} else . end) | map(if .key == "Token" then . + {"key":"AWS_SESSION_TOKEN"} else . end) | map("export \(.key)=\(.value)") | .[]' -r > /tmp/aws_cred_export.txt # work around https://github.com/hashicorp/terraform/issues/8746
      - wget https://releases.hashicorp.com/terraform/0.10.3/terraform_0.10.3_linux_amd64.zip
      - unzip terraform_0.10.3_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.10.3_linux_amd64.zip
      - apt-get update
      - source /tmp/aws_cred_export.txt && terraform --version
      - source /tmp/aws_cred_export.txt && terraform init
  build:
    commands:
      - source /tmp/aws_cred_export.txt && terraform apply
      - echo "Post apply build"
  post_build:
    commands:
      - command
      - echo 'post_build nothing to do for now'